### ISSUE TITLE
failed compile with nginx-1.9.13

### ISSUE THREAD

**Issue by gfrankliu** [GUI/nginx-upstream-dynamic-servers#15]
./configure --add-module=nginx-upstream-dynamic-servers
make
...
```
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules \
		-o objs/src/http/modules/ngx_http_upstream_zone_module.o \
		src/http/modules/ngx_http_upstream_zone_module.c
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g   -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules \
		-o objs/addon/nginx-upstream-dynamic-servers/ngx_http_upstream_dynamic_servers.o \
		nginx-upstream-dynamic-servers/ngx_http_upstream_dynamic_servers.c
cc1: warnings being treated as errors
nginx-upstream-dynamic-servers/ngx_http_upstream_dynamic_servers.c: In function ‘ngx_http_upstream_dynamic_server_resolve_handler’:
nginx-upstream-dynamic-servers/ngx_http_upstream_dynamic_servers.c:425: error: assignment from incompatible pointer type
nginx-upstream-dynamic-servers/ngx_http_upstream_dynamic_servers.c:438: error: assignment from incompatible pointer type
make[1]: *** [objs/addon/nginx-upstream-dynamic-servers/ngx_http_upstream_dynamic_servers.o] Error 1
```

**Comment by wandenberg** [comment]
I couldn't reproduce the problem. Which gcc version are you using?

**Comment by gfrankliu** [comment]
It's centos 6. I'm not on the computer right now to check the exact gcc version that comes with latest centos 6.

**Comment by gfrankliu** [comment]
gcc-4.4.7-16.el6.x86_64

**Comment by wandenberg** [comment]
@gfrankliu can you test this [version](https://github.com/wandenberg/nginx-upstream-dynamic-servers/tree/nginx_1_9_13) ?
it should compile and run normally

**Comment by gfrankliu** [comment]
same error on cents 6.
tar zxf nginx-1.9.13.tar.gz
cd nginx-1.9.13
git clone https://github.com/wandenberg/nginx-upstream-dynamic-servers.git
./configure --add-module=nginx-upstream-dynamic-servers
make

**Comment by wandenberg** [comment]
You picked the wrong version. The link target to nginx_1_9_13 branch, not to master.
Retry after checkout to it, please.

**Comment by gfrankliu** [comment]
switched to the nginx_1_9_13 and it is working. Thanks!
